linters-settings:
  gofumpt:
    extra-rules: true
  goimports:
    local-prefixes: github.com/pact-im
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      - log
    packages-with-error-message:
      - log: "use go.uber.org/zap instead"

linters:
  enable:
    - gofumpt
    - goimports
    - depguard
    - gocritic
    - misspell
