name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2
      - name: Set up Go
        uses: actions/setup-go@v3.2.0
        with:
          go-version-file: .go-version
          cache: true
          cache-dependency-path: '**/go.sum'
      - name: Run tests
        run: go test -race go.pact.im/x/...
